version: "3.3"
services:
  urus-inventory-web:
    image: danaiid/urus-inventory-web
    environment:
      - QUARKUS_DATASOURCE_DB-KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=daksa
      - QUARKUS_DATASOURCE_PASSWORD=d4ksa@123
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://pgm-d9jv2hy1o3e6gaq0.pgsql.ap-southeast-5.rds.aliyuncs.com:1921/urus-inventory-web
      - QUARKUS_LOG_FILE.ENABLE=true
      - QUARKUS_LOG_LEVEL=INFO
      - QUARKUS_LOG_MIN-LEVEL=ALL
      - QUARKUS_LOG_FILE_PATH=/tmp/urus-inventory-web.log
      - QUARKUS_LOG_CATEGORY_"com.adiwisista"_LEVEL=ALL
      - DIR_PDF = /deployment/upload/
    volumes:
      - /home/adiwisista/docker/upload:/deployments/upload:z
    user: root
    ports:
      - 15002:15002
networks:
  danai-net:
    external: true